title: Kamus Psikologi
email: 
description: >- 
  Kamus Istilah Psikologi Indonesia.
baseurl: "/kamus-psikologi" 
url: "https://nidowardana.github.io" 
twitter_username: 
github_username:  

# Build settings
theme: minima
plugins:
  - jekyll-feed


collections:
  terms:
    output: true
    permalink: /istilah/:name/

