title: Kamus Psikologi
email: 
description: >- 
  Kamus Istilah Psikologi Indonesia.
baseurl: "" 
url: "https://kamuspsikologi.id" 
twitter_username: 
github_username:  

# Build settings
theme: minima
plugins:
  - jekyll-feed


collections:
  terms:
    output: true
    permalink: /istilah/:name/
